create table if not exists vastgoedkompas_submissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  payload jsonb not null
);

create index if not exists vastgoedkompas_submissions_created_at_idx
on vastgoedkompas_submissions (created_at desc);

create index if not exists vastgoedkompas_submissions_type_idx
on vastgoedkompas_submissions ((payload->>'type'));
